PalmerPetsProject/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Available_Deals__c</fullName>
        <description>The remaining number of times a deal can be accepted</description>
        <formula>Max_Acceptances__c  -  Acceptances__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Deals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <description>The date a deal is available through</description>
        <label>Valid Through</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PalmerPetsProject/src/objects/Deal_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deal Actions</relationshipLabel>
        <relationshipName>Deal_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Actions</relationshipLabel>
        <relationshipName>Deal_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Action</label>
    <nameField>
        <displayFormat>DA-{0000}</displayFormat>
        <label>Deal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PalmerPetsProject/src/classes/DealViewerFrontController.cls
public class DealViewerFrontController {
	String contactId = ApexPages.currentPage().getParameters().get('contactId');
    Contact contact;
   	List<DisplayOffers> dealsList;
    
    public List<DisplayOffers> getOffers() {
        if(dealsList==null){
            dealsList = new List<DisplayOffers>();
            for(Deal_Action__c item: [
                Select action__c, contact__r.name,deal__r.name from deal_action__c]){
                    dealsList.add(new DisplayOffers(item));
                }
        }
        return dealsList;
    }

    
    public class DisplayOffers{
        private Deal_Action__c dealAction;
        
        public DisplayOffers(Deal_Action__c item){
        	this.dealAction = item;    
        }

        private String status
        {
            get{ return dealAction.Action__c; }
            
        }
        private String icon{
            get { return 'defaultIcon';}
        }
        private String dealName
        {
            get{ return dealAction.Deal__r.name; }
        }
        private Date validThrough
        {
            get{ return dealAction.Deal__r.valid_through__c; }
        }
        public Decimal availableDeals{
            get { return dealAction.Deal__r.available_deals__c; }
        }
    }
}